#!/bin/sh

# Install Java 7
export DEBIAN_FRONTEND=noninteractive
apt-get install -q -y software-properties-common
#apt-get install -q -y python-software-properties
apt-add-repository ppa:webupd8team/java -y
apt-get update
echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
apt-get install oracle-java7-installer -y
apt-get clean

